version: '3.8'

services:
  aidx-jupyter:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: tslaroadster/aidx-model-development:latest
    network_mode: "host"
    restart: on-failure
    volumes:
      - ~/workspace:/workspace-host
    working_dir: "/workspace"
    command: "docker/run-jupyter.sh"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    stdin_open: true
    tty: true