version: '3.8'

services:
  lambda-stack:
    build:
      context: https://github.com/lambdal/lambda-stack-dockerfiles.git
      dockerfile: Dockerfile.jammy
    image: lambda-stack:22.04
  aidx-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - lambda-stack
    network_mode: "host"
    restart: always
    volumes:
      - /home/alan/workspace:/workspace
    command: "jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --NotebookApp.password=''"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    stdin_open: true
    tty: true