version: '3.8'

services:
  delta-ai:
    build:
      context: https://github.com/lambdal/lambda-stack-dockerfiles.git
      dockerfile: Dockerfile.jammy
    image: lambda-stack:22.04
    ports:
      - "8888:8888" # Port forwarding for Jupyter Notebook
    environment:
      - HOST_IP=${HOST_IP}
    restart: always
    volumes:
      - /home/alan/workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    stdin_open: true
    tty: true
