version: '3.8'

services:
  lambda-stack:
    build:
      context: https://github.com/lambdal/lambda-stack-dockerfiles.git
      dockerfile: Dockerfile.jammy
    image: lambda-stack:22.04
  aidx-jupyter:
    depends_on:
      - lambda-stack
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: tslaroadster/aidx-model-development:latest
    network_mode: "host"
    restart: on-failure
    volumes:
      - ~/workspace:/workspace-host
    working_dir: "/workspace"
    command: "docker/run-jupyter.sh"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    stdin_open: true
    tty: true